"""Predict cervical cancer risk for a single patient.

Loads the trained CerviRisk-MM v0.1 pipeline and exposes a single function
that takes a patient feature dictionary and returns:
  - calibrated risk probability
  - risk tier (low/moderate/high)
  - top contributing features (placeholder; SHAP wired in later)
  - data status (SYNTHETIC_ASSEMBLY for augmented patients)
"""
from __future__ import annotations

import json
import logging
from typing import Any

import joblib
import numpy as np
import pandas as pd

from src.storage.paths import MODELS_DIR

logger = logging.getLogger(__name__)


MODEL_PATH = MODELS_DIR / "cervirisk_mm_v0.1.pkl"

# Risk tier thresholds — population percentile based.
# Calibrated to UCI test-set distribution; revisit when real-data deployment.
TIER_THRESHOLDS = {"low_max": 0.05, "moderate_max": 0.20}


_pipeline = None


def load_model():
    global _pipeline
    if _pipeline is None:
        if not MODEL_PATH.exists():
            raise FileNotFoundError(
                f"No trained model at {MODEL_PATH}. Run `python -m src.model.train` first."
            )
        _pipeline = joblib.load(MODEL_PATH)
        logger.info("Loaded model from %s", MODEL_PATH)
    return _pipeline


def _tier_for(p: float) -> str:
    if p < TIER_THRESHOLDS["low_max"]:
        return "low"
    if p < TIER_THRESHOLDS["moderate_max"]:
        return "moderate"
    return "high"


def predict(patient: dict[str, Any]) -> dict[str, Any]:
    """Score one patient.

    patient: dict of feature_name -> value. Should include the columns the
        trained pipeline expects. Missing values are accepted (the pipeline
        imputes them).

    Returns:
        dict with keys:
          - risk_probability (float, 0-1)
          - tier (str: low / moderate / high)
          - data_status (str: SYNTHETIC_ASSEMBLY by default for v0.1)
          - model_version (str)
          - disclaimer (str)
    """
    pipe = load_model()
    df = pd.DataFrame([patient])
    proba = float(pipe.predict_proba(df)[0, 1])

    return {
        "risk_probability": round(proba, 4),
        "tier": _tier_for(proba),
        "data_status": patient.get("data_status", "SYNTHETIC_ASSEMBLY"),
        "model_version": "cervirisk_mm_v0.1",
        "disclaimer": (
            "This prediction is generated by a research prototype trained on "
            "the UCI Cervical Cancer Risk Factors dataset (n=858) with biological "
            "augmentations from public sources. It is not a medical diagnosis. "
            "See docs/DATA_PROVENANCE.md for the full integrity contract."
        ),
    }


def main() -> None:
    """CLI smoke test: score a hardcoded example patient."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s | %(message)s")

    # Synthetic example patient — should not be interpreted clinically.
    example = {
        "Age": 38.0,
        "Number of sexual partners": 4.0,
        "First sexual intercourse": 16.0,
        "Num of pregnancies": 2.0,
        "Smokes": 1.0,
        "Smokes (years)": 12.0,
        "Hormonal Contraceptives": 1.0,
        "Hormonal Contraceptives (years)": 6.0,
        "IUD": 0.0,
        "IUD (years)": 0.0,
        "STDs": 1.0,
        "STDs (number)": 1.0,
        "STDs:HPV": 1.0,
        "STDs:HIV": 0.0,
        "Dx:Cancer": 0.0,
        "Dx:CIN": 0.0,
        "Dx:HPV": 1.0,
        "strain_carcinogenicity": 0.95,    # HPV16 assigned
        "host_prs": 0.3,                    # placeholder PRS
        "assigned_hpv_strain": "HPV16",
        "matched_super_pop": "AMR",
    }

    result = predict(example)
    print()
    print("Example prediction:")
    print(json.dumps(result, indent=2))
    print()


if __name__ == "__main__":
    main()
